require('dotenv').config();
const { connectDB, disconnectDB } = require('./src/config/database');
const Doctor = require('./src/models/Doctor');
const bcrypt = require('bcryptjs');

const seedDoctors = [
  {
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh.kumar@hospital.com',
    phone: '9876543210',
    password: 'Password123',
    specialization: 'Cardiologist',
    licenseNumber: 'LIC001234',
    yearsOfExperience: 12,
    qualifications: [
      { degree: 'MBBS', institution: 'Delhi Medical College', yearOfCompletion: 2012 },
      { degree: 'MD', institution: 'AIIMS Delhi', yearOfCompletion: 2015 },
    ],
    medicalRegistration: {
      number: 'REG001234',
      authority: 'Medical Council of India',
      registrationDate: new Date('2012-06-15'),
    },
    clinic: {
      name: 'Heart Care Clinic',
      address: '123, MG Road',
      city: 'Delhi',
      state: 'Delhi',
      zipCode: '110001',
      phone: '011-2234567',
    },
    consultationFee: 500,
    workingHours: {
      monday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '10:00', endTime: '14:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/rajesh.jpg',
    bio: 'Expert cardiologist with 12 years of experience in treating heart conditions.',
    languages: ['English', 'Hindi'],
    averageRating: 4.8,
    totalRatings: 120,
    totalAppointments: 450,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-01'),
  },
  {
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@hospital.com',
    phone: '9876543211',
    password: 'Password123',
    specialization: 'Dermatologist',
    licenseNumber: 'LIC001235',
    yearsOfExperience: 8,
    qualifications: [
      { degree: 'MBBS', institution: 'CMC Vellore', yearOfCompletion: 2016 },
      { degree: 'MD', institution: 'PGIMER Chandigarh', yearOfCompletion: 2019 },
    ],
    medicalRegistration: {
      number: 'REG001235',
      authority: 'Medical Council of India',
      registrationDate: new Date('2016-05-20'),
    },
    clinic: {
      name: 'Skin Care Center',
      address: '456, Bandra Street',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400050',
      phone: '022-2234567',
    },
    consultationFee: 400,
    workingHours: {
      monday: { startTime: '10:00', endTime: '19:00', isAvailable: true },
      tuesday: { startTime: '10:00', endTime: '19:00', isAvailable: true },
      wednesday: { startTime: '10:00', endTime: '19:00', isAvailable: true },
      thursday: { startTime: '10:00', endTime: '19:00', isAvailable: true },
      friday: { startTime: '10:00', endTime: '19:00', isAvailable: true },
      saturday: { startTime: '11:00', endTime: '16:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/priya.jpg',
    bio: 'Specialized in cosmetic and clinical dermatology with focus on skin disorders.',
    languages: ['English', 'Hindi', 'Marathi'],
    averageRating: 4.6,
    totalRatings: 95,
    totalAppointments: 320,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-05'),
  },
  {
    firstName: 'Amit',
    lastName: 'Singh',
    email: 'amit.singh@hospital.com',
    phone: '9876543212',
    password: 'Password123',
    specialization: 'Orthopedist',
    licenseNumber: 'LIC001236',
    yearsOfExperience: 15,
    qualifications: [
      { degree: 'MBBS', institution: 'St Johns Medical College', yearOfCompletion: 2009 },
      { degree: 'DM', institution: 'AIIMS Delhi', yearOfCompletion: 2012 },
    ],
    medicalRegistration: {
      number: 'REG001236',
      authority: 'Medical Council of India',
      registrationDate: new Date('2009-04-10'),
    },
    clinic: {
      name: 'Bone and Joints Clinic',
      address: '789, Park Lane',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560001',
      phone: '080-2234567',
    },
    consultationFee: 600,
    workingHours: {
      monday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      tuesday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      wednesday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      thursday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      friday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      saturday: { startTime: '09:00', endTime: '13:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/amit.jpg',
    bio: 'Senior orthopedic surgeon with expertise in joint replacement and sports injuries.',
    languages: ['English', 'Hindi', 'Kannada'],
    averageRating: 4.9,
    totalRatings: 140,
    totalAppointments: 520,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-08'),
  },
  {
    firstName: 'Neha',
    lastName: 'Patel',
    email: 'neha.patel@hospital.com',
    phone: '9876543213',
    password: 'Password123',
    specialization: 'Pediatrician',
    licenseNumber: 'LIC001237',
    yearsOfExperience: 10,
    qualifications: [
      { degree: 'MBBS', institution: 'Manipal University', yearOfCompletion: 2014 },
      { degree: 'MD', institution: 'PGIMER Chandigarh', yearOfCompletion: 2017 },
    ],
    medicalRegistration: {
      number: 'REG001237',
      authority: 'Medical Council of India',
      registrationDate: new Date('2014-08-22'),
    },
    clinic: {
      name: 'Kids Care Pediatric Center',
      address: '321, Sector 7',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500032',
      phone: '040-2234567',
    },
    consultationFee: 350,
    workingHours: {
      monday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '10:00', endTime: '15:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/neha.jpg',
    bio: 'Child specialist with expertise in developmental pediatrics and immunization.',
    languages: ['English', 'Hindi', 'Telugu'],
    averageRating: 4.7,
    totalRatings: 110,
    totalAppointments: 380,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-12'),
  },
  {
    firstName: 'Vikram',
    lastName: 'Gupta',
    email: 'vikram.gupta@hospital.com',
    phone: '9876543214',
    password: 'Password123',
    specialization: 'Neurologist',
    licenseNumber: 'LIC001238',
    yearsOfExperience: 14,
    qualifications: [
      { degree: 'MBBS', institution: 'Delhi Medical College', yearOfCompletion: 2010 },
      { degree: 'MD', institution: 'AIIMS Delhi', yearOfCompletion: 2013 },
    ],
    medicalRegistration: {
      number: 'REG001238',
      authority: 'Medical Council of India',
      registrationDate: new Date('2010-07-05'),
    },
    clinic: {
      name: 'Neurology Care Clinic',
      address: '654, Medical Lane',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411001',
      phone: '020-2234567',
    },
    consultationFee: 550,
    workingHours: {
      monday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/vikram.jpg',
    bio: 'Expert neurologist specializing in migraine, epilepsy, and neurological disorders.',
    languages: ['English', 'Hindi'],
    averageRating: 4.5,
    totalRatings: 85,
    totalAppointments: 290,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-15'),
  },
  {
    firstName: 'Ananya',
    lastName: 'Verma',
    email: 'ananya.verma@hospital.com',
    phone: '9876543215',
    password: 'Password123',
    specialization: 'Gynecologist',
    licenseNumber: 'LIC001239',
    yearsOfExperience: 11,
    qualifications: [
      { degree: 'MBBS', institution: 'CMC Vellore', yearOfCompletion: 2013 },
      { degree: 'MD', institution: 'JIPMER Puducherry', yearOfCompletion: 2016 },
    ],
    medicalRegistration: {
      number: 'REG001239',
      authority: 'Medical Council of India',
      registrationDate: new Date('2013-06-11'),
    },
    clinic: {
      name: "Women's Health Center",
      address: '987, Health Street',
      city: 'Chennai',
      state: 'Tamil Nadu',
      zipCode: '600001',
      phone: '044-2234567',
    },
    consultationFee: 450,
    workingHours: {
      monday: { startTime: '10:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '10:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '10:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '10:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '10:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '11:00', endTime: '15:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/ananya.jpg',
    bio: 'Experienced gynecologist providing comprehensive women health services.',
    languages: ['English', 'Hindi', 'Tamil'],
    averageRating: 4.8,
    totalRatings: 125,
    totalAppointments: 420,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-18'),
  },
  {
    firstName: 'Sanjay',
    lastName: 'Malhotra',
    email: 'sanjay.malhotra@hospital.com',
    phone: '9876543216',
    password: 'Password123',
    specialization: 'Endocrinologist',
    licenseNumber: 'LIC001240',
    yearsOfExperience: 13,
    qualifications: [
      { degree: 'MBBS', institution: 'St Johns Medical College', yearOfCompletion: 2011 },
      { degree: 'MD', institution: 'AIIMS Delhi', yearOfCompletion: 2014 },
    ],
    medicalRegistration: {
      number: 'REG001240',
      authority: 'Medical Council of India',
      registrationDate: new Date('2011-05-18'),
    },
    clinic: {
      name: 'Endocrinology Clinic',
      address: '147, Medical Complex',
      city: 'Jaipur',
      state: 'Rajasthan',
      zipCode: '302001',
      phone: '0141-2234567',
    },
    consultationFee: 500,
    workingHours: {
      monday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '10:00', endTime: '14:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/sanjay.jpg',
    bio: 'Specialist in diabetes, thyroid disorders, and hormonal imbalances.',
    languages: ['English', 'Hindi'],
    averageRating: 4.6,
    totalRatings: 100,
    totalAppointments: 350,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-20'),
  },
  {
    firstName: 'Sneha',
    lastName: 'Iyer',
    email: 'sneha.iyer@hospital.com',
    phone: '9876543217',
    password: 'Password123',
    specialization: 'Pulmonologist',
    licenseNumber: 'LIC001241',
    yearsOfExperience: 9,
    qualifications: [
      { degree: 'MBBS', institution: 'Manipal University', yearOfCompletion: 2015 },
      { degree: 'MD', institution: 'PGIMER Chandigarh', yearOfCompletion: 2018 },
    ],
    medicalRegistration: {
      number: 'REG001241',
      authority: 'Medical Council of India',
      registrationDate: new Date('2015-09-14'),
    },
    clinic: {
      name: 'Respiratory Care Center',
      address: '258, Health Avenue',
      city: 'Cochin',
      state: 'Kerala',
      zipCode: '682001',
      phone: '0484-2234567',
    },
    consultationFee: 400,
    workingHours: {
      monday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      tuesday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      wednesday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      thursday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      friday: { startTime: '08:00', endTime: '17:00', isAvailable: true },
      saturday: { startTime: '09:00', endTime: '13:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/sneha.jpg',
    bio: 'Respiratory specialist with focus on asthma, COPD and lung diseases.',
    languages: ['English', 'Hindi', 'Malayalam'],
    averageRating: 4.4,
    totalRatings: 75,
    totalAppointments: 250,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-22'),
  },
  {
    firstName: 'Arun',
    lastName: 'Nair',
    email: 'arun.nair@hospital.com',
    phone: '9876543218',
    password: 'Password123',
    specialization: 'Gastroenterologist',
    licenseNumber: 'LIC001242',
    yearsOfExperience: 16,
    qualifications: [
      { degree: 'MBBS', institution: 'Delhi Medical College', yearOfCompletion: 2008 },
      { degree: 'MD', institution: 'AIIMS Delhi', yearOfCompletion: 2011 },
    ],
    medicalRegistration: {
      number: 'REG001242',
      authority: 'Medical Council of India',
      registrationDate: new Date('2008-03-20'),
    },
    clinic: {
      name: 'Digestive Health Clinic',
      address: '369, Healthcare Plaza',
      city: 'Kolkata',
      state: 'West Bengal',
      zipCode: '700001',
      phone: '033-2234567',
    },
    consultationFee: 550,
    workingHours: {
      monday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '10:00', endTime: '14:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/arun.jpg',
    bio: 'Expert in digestive disorders with advanced endoscopy procedures.',
    languages: ['English', 'Hindi', 'Bengali'],
    averageRating: 4.7,
    totalRatings: 130,
    totalAppointments: 470,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-25'),
  },
  {
    firstName: 'Meera',
    lastName: 'Dutta',
    email: 'meera.dutta@hospital.com',
    phone: '9876543219',
    password: 'Password123',
    specialization: 'Ophthalmologist',
    licenseNumber: 'LIC001243',
    yearsOfExperience: 12,
    qualifications: [
      { degree: 'MBBS', institution: 'CMC Vellore', yearOfCompletion: 2012 },
      { degree: 'MD', institution: 'JIPMER Puducherry', yearOfCompletion: 2015 },
    ],
    medicalRegistration: {
      number: 'REG001243',
      authority: 'Medical Council of India',
      registrationDate: new Date('2012-08-24'),
    },
    clinic: {
      name: 'Eye Care Center',
      address: '741, Vision Street',
      city: 'Ahmedabad',
      state: 'Gujarat',
      zipCode: '380001',
      phone: '079-2234567',
    },
    consultationFee: 400,
    workingHours: {
      monday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      tuesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      wednesday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      thursday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      friday: { startTime: '09:00', endTime: '18:00', isAvailable: true },
      saturday: { startTime: '10:00', endTime: '15:00', isAvailable: true },
      sunday: { startTime: '00:00', endTime: '00:00', isAvailable: false },
    },
    slotDuration: 30,
    profilePicture: '/profile-pics/meera.jpg',
    bio: 'Experienced eye care specialist offering comprehensive ophthalmology services.',
    languages: ['English', 'Hindi', 'Gujarati'],
    averageRating: 4.5,
    totalRatings: 105,
    totalAppointments: 380,
    isActive: true,
    isApproved: true,
    approvalDate: new Date('2023-01-28'),
  },
];

(async () => {
  try {
    await connectDB();
    console.log('Connected to database');

    // Delete existing doctors (optional - comment out to keep existing data)
    // await Doctor.deleteMany({});
    // console.log('Deleted existing doctors');

    // Insert doctors one-by-one so the pre-save bcrypt hook runs on each
    const insertedDoctors = [];
    for (const data of seedDoctors) {
      const doctor = new Doctor(data);
      await doctor.save();
      insertedDoctors.push(doctor);
    }
    console.log(`✓ Successfully seeded ${insertedDoctors.length} doctors!`);
    console.log('\nSeeded Doctor IDs:');
    insertedDoctors.forEach((doc, index) => {
      console.log(`${index + 1}. ${doc.firstName} ${doc.lastName} - ID: ${doc._id}`);
    });

    process.exit(0);
  } catch (error) {
    console.error('Error seeding doctors:', error);
    process.exit(1);
  }
})();
